### ISSUE TITLE
Error processing mpqa

### ISSUE THREAD

**Issue by MinionAttack** [jerbarnes/semeval22_structured_sentiment#1]
Hi,

I'm trying to do the [Step 1](https://github.com/jerbarnes/semeval22_structured_sentiment/tree/master/data#step-1) but I'm getting this error for the MPQA 2.0 corpus:

```
2021-09-07 14:50:30 INFO: Loading these models for language: en (English):
========================
| Processor | Package  |
------------------------
| tokenize  | combined |
========================

2021-09-07 14:50:30 INFO: Use device: gpu
2021-09-07 14:50:30 INFO: Loading: tokenize
2021-09-07 14:50:38 INFO: Done loading processors!
  0%|                                                                                                                                                                           | 0/287 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "process_mpqa.py", line 355, in <module>
    main()
  File "process_mpqa.py", line 343, in main
    new = process_file(fname, nlp)
  File "process_mpqa.py", line 315, in process_file
    sents = get_sents(text, fname, nlp)
  File "process_mpqa.py", line 189, in get_sents
    sent_bidx = int(sentence.tokens[0].misc.split("|")[0].split("=")[1])
AttributeError: 'NoneType' object has no attribute 'split'
```
For the Darmstadt Service Review Corpus I have no problems.

**Comment by jerbarnes** [comment]
Looks like it was due to old stanza. Updated the code to work for >=1.2.3. Let me know if it works for you and if so, I'll close the issue.

**Comment by MinionAttack** [comment]
HI jerbarnes, I'm still having the same problem even with stanza==1.2.3.

**Comment by jerbarnes** [comment]
Have you pulled the changes? If so, what error do you get now, because it shouldn't be possible to get the same error as before.

**Comment by MinionAttack** [comment]
Oops, sorry, I forgot to pull the changes! What a rookie mistake.
