### ISSUE TITLE
Error when uploading the file with the predictions

### ISSUE THREAD

**Issue by MinionAttack** [jerbarnes/semeval22_structured_sentiment#21]
Hi,

I've uploaded the submission file and after a while I've seen that the status changed to "Failed".

Looking at the output file I can see in the "Scoring output log" something like this:

```
monolingual
########################################
SF1 on norec: XXXX
SF1 on multibooked_ca: XXXX
SF1 on multibooked_eu: XXXX
SF1 on opener_en: XXXX
SF1 on opener_es: XXXX
```

And If I see in the "Scoring error log":

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpA_k0h4/run/program/evaluate.py", line 269, in <module>
    main()
  File "/tmp/codalab/tmpA_k0h4/run/program/evaluate.py", line 246, in main
    assert g.issubset(p), "missing some sentences: {}".format(g.difference(p))
AssertionError: missing some sentences: set([u'20020507/22.11.06-28210-40', u'xbank/wsj_0189-15', u'xbank/wsj_0266-8', u'ula/sw2078-UTF16-ms98-a-trans-211', u'ula/sw2078-UTF16-ms98-a-trans-210', u'non_fbis/16.01.33-12919-50', u'20020507/17.55.53-20579-19', u'xbank/wsj_0762-6', u'xbank/wsj_1033-10', u'20020316/20.37.48-18053-23', u'20020316/20.37.48-18053-24', u'xbank/wsj_0679-11', u'non_fbis/16.01.33-12919-49', u'non_fbis/16.01.33-12919-48', u'non_fbis/06.12.31-26764-20', u'non_fbis/12.15.47-5091-24', u'xbank/wsj_0176-7', u'xbank/wsj_0189-17', u'xbank/wsj_0557-20', u'xbank/wsj_0173-10', u'xbank/wsj_0144-9', u'xbank/wsj_0136-7', u'20020517/22.08.22-24562-15', u'20020517/22.08.22-24562-16', u'20020517/22.08.22-24562-17', u'20011130/12.33.55-762-10', u'20011130/12.33.55-762-11', u'20011204/21.34.10-25509-4', u'non_fbis/09.35.06-27851-12', u'xbank/wsj_0068-6', u'20020320/12.04.40-21590-29', u'20020517/22.08.22-24562-18', u'20020302/21.01.08-20603-7', u'ula/sw2078-UTF16-ms98-a-trans-207', u'ula/sw2015-ms98-a-trans-41', u'ula/sw2015-ms98-a-trans-40', u'ula/115CVL035-17', u'ula/115CVL035-16', u'20020411/22.23.02-12197-18', u'ula/110CYL068-31', u'xbank/wsj_0679-10', u'ula/sw2078-UTF16-ms98-a-trans-208', u'ula/sw2078-UTF16-ms98-a-trans-209', u'xbank/wsj_1038-9', u'xbank/wsj_0991-6', u'xbank/wsj_0679-9', u'ula/110CYL200-23', u'20010620/13.40.05-15087-17', u'20020123/21.21.45-6259-23', u'xbank/wsj_0551-4', u'20010706/02.01.27-21386-7', u'xbank/wsj_0068-7', u'xbank/wsj_0189-16', u'20020507/22.11.06-28210-39', u'ula/115CVL035-15', u'xbank/wsj_0173-9', u'xbank/wsj_0811-11', u'ula/115CVL035-14'])
```
I see that the `MPQA` and `darmstadt_unis` datasets are missing, but I've updated the data and executed the pre-processing scripts after the changes made in the 29.11.2021 before training and predicting the files.

Before the submission I've obtained the scores locally with the file `evaluate_single_dataset.py` and I can get the scores for all datasets in monolingual and for the crosslingual task.

What I'm doing wrong?

Regards.

**Comment by jerbarnes** [comment]
Hey,

I just downloaded your submission and for me locally I get the same error, so it seems there are some differences in your processed MPQA data. There were some problems that came about from using different stanza versions. In the end, I had to add a requirements.txt for the data processing step as well, as there were several people who were having problems. You should have 2063 dev sentences, so maybe you can check if you have that or not?

**Comment by MinionAttack** [comment]
Seeing the requirements it's specified `stanza=1.1.1` but some time ago I opened and issue #1 and the code was updated to use `stanza >=1.2.3` so this is a regression?

**Comment by jerbarnes** [comment]
More than a regression, it seems there were some differences between 1.1.1 and 1.2.3 that came up when dealing with further issues. I think I've fixed some of the problems that gave the original error while using 1.1.1 in #1. Could you try with that and see if it helps? Sorry for the back and forth :/

**Comment by MinionAttack** [comment]
Hi, creating a virtualenv from scratch and installing:

```
torch==1.3.1
matplotlib==3.1.2
scikit-learn==0.21.0
gensim==3.8.1
stanza==1.1.1
nltk==3.4.5
```
`sklearn` has been replaced with `scikit-learn`. I get this error:

```
2021-12-09 22:29:29 INFO: Loading these models for language: en (English):
========================
| Processor | Package  |
------------------------
| tokenize  | combined |
========================

2021-12-09 22:29:29 INFO: Use device: gpu
2021-12-09 22:29:29 INFO: Loading: tokenize
Traceback (most recent call last):
  File "process_mpqa.py", line 416, in <module>
    main()
  File "process_mpqa.py", line 397, in main
    nlp = stanza.Pipeline("en", processors='tokenize')
  File "/home/iago/Escritorio/SemEval-2022_Shared_Task_10/env/lib/python3.6/site-packages/stanza/pipeline/core.py", line 113, in __init__
    use_gpu=self.use_gpu)
  File "/home/iago/Escritorio/SemEval-2022_Shared_Task_10/env/lib/python3.6/site-packages/stanza/pipeline/processor.py", line 146, in __init__
    self._set_up_model(config, use_gpu)
  File "/home/iago/Escritorio/SemEval-2022_Shared_Task_10/env/lib/python3.6/site-packages/stanza/pipeline/tokenize_processor.py", line 38, in _set_up_model
    self._trainer = Trainer(model_file=config['model_path'], use_cuda=use_gpu)
  File "/home/iago/Escritorio/SemEval-2022_Shared_Task_10/env/lib/python3.6/site-packages/stanza/models/tokenize/trainer.py", line 19, in __init__
    self.load(model_file)
  File "/home/iago/Escritorio/SemEval-2022_Shared_Task_10/env/lib/python3.6/site-packages/stanza/models/tokenize/trainer.py", line 91, in load
    self.model.load_state_dict(checkpoint['model'])
  File "/home/iago/Escritorio/SemEval-2022_Shared_Task_10/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tokenizer:
	Missing key(s) in state_dict: "mwt_clf.weight", "mwt_clf.bias", "mwt_clf2.weight". 
```

**Comment by MinionAttack** [comment]
Installing an environment with stanza 1.1.1 gives me a dev.json with 2063 sentences.

**Comment by jerbarnes** [comment]
Great. Have you tried to resubmit?

**Comment by MinionAttack** [comment]
Not yet, I'm retraining the models.

**Comment by MinionAttack** [comment]
I have a question, now that I am using stanza 1.1.1 do I have to retrain all baseline models or just MPQA?

**Comment by jerbarnes** [comment]
MPQA is the only dataset that was affected by the stanza version issue, as
far as I know.

Iago Alonso Alonso ***@***.***> igorleak hau idatzi zuen
(2021 abe. 10, or. 13:14):

**Comment by MinionAttack** [comment]
Done, now it works.
